"""fifth Migration

Revision ID: 84849655fb34
Revises: fd4ebacb0ba7
Create Date: 2021-06-21 14:49:55.548737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84849655fb34'
down_revision = 'fd4ebacb0ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    # ### end Alembic commands ###
